### ISSUE TITLE
HIV drug resistance

### ISSUE THREAD

**Issue by Anastasiamiaomiao** [PoonLab/MiCall-Lite#35]
Hi, 
I have encountered problems in analyzing HIV drug resistance. 

1. The running commands and prompt errors are as follows:
![780606979c7b9c23d1a87940511e93c](https://user-images.githubusercontent.com/41099785/65669135-965d4080-e075-11e9-9388-79d346dd5db6.png)
![514bcb658c4690e2e29d6560c598789](https://user-images.githubusercontent.com/41099785/65669138-965d4080-e075-11e9-8393-f795e3cfff8a.png)
![ffbe334b1b45a06376162fb5f357774](https://user-images.githubusercontent.com/41099785/65669293-de7c6300-e075-11e9-836f-5e7ec957d80a.png)

2. Now only S34 can get results, the .tsv file for each sample is as follows:
![d2caad7c7c2da4559ec1f01a8893326](https://user-images.githubusercontent.com/41099785/65669701-a295cd80-e076-11e9-9cf1-007fe3001a10.png)

**Comment by ArtPoon** [comment]
Hi @Anastasiamiaomiao, sorry to hear you're having problems with the resistance scoring script.  I've re-enabled the account on my server, would you be able to upload your sequences vi SFTP so I can try to reproduce the issue?

**Comment by ArtPoon** [comment]
In the meantime I wlil investigate the error messages you posted.

**Comment by ArtPoon** [comment]
For your samples that `scoreHIVdb.py` failed on, did those reads map to HIV-1 *pol*?  

I am looking at the `S10` FASTQ files that you uploaded to my server (so I could help you with issue #25) and those reads were very short and mapped to *gag*.

**Comment by ArtPoon** [comment]
@Anastasiamiaomiao I'm examining the error messages that you posted.  These both affect the same `subtyper` function within `sierra-local` (they're not MiCall issues, strictly speaking).  This function attempts to calculate the p-distance (relative number of nucleotide differences) between two aligned sequences.

In the first case (S1), the function fails because `seq` is an empty string.  Now, I'm fairly sure that your input (`S1.csv`) is a `conseq` output file because there's a check for this in the `scoreHIVdb.py` script.    Beyond this, it is difficult for me to debug the problem.  Can you confirm for me that the consensus sequences in `S1.csv` are non-empty strings, i.e., nucleotide sequences of non-zero length?

If you could do a secure file transfer (sftp) to my server, that would be a big help.

**Comment by Anastasiamiaomiao** [comment]
Thank you very much for your response.
The file has been completed by sftp transfer.

**Comment by ArtPoon** [comment]
Files received, thanks.  I have locked the user account for security - let me know whenever you want access re-enabled.

I have confirmed that the consensus sequence files appear to be correct, and I have reproduced the `KeyError: ' '` issue.  Some extra space characters are getting introduced into the input sequence string for some reason.  Looking into it.

**Comment by ArtPoon** [comment]
Diagnosed this as a long-standing issue in PoonLab/sierra-local#50

Basically, HIVdb's nucamino has a really complicated format for indels and we haven't gotten around to parsing the aligned sequence correctly.  This only affected their subtyping method, which we found had a negligible effect on the accuracy of resistance scoring.  However, this is introducing extraneous spaces into the nucleotide sequence string.

Which means that I've got to fix this now :(

**Comment by ArtPoon** [comment]
Ok, I have turned off subtyping in the `sierralocal` master branch until I have this figured out.  This allows you to process your `conseq` outputs with the `scoreHIVdb.py` script normally.  

Please pull from the **sierra-local** master branch and recompile with `sudo python3 setup.py install` before re-running `scoreHIVdb.py`

Updates will be posted to PoonLab/sierra-local#50

**Comment by Anastasiamiaomiao** [comment]
Ok, thank you. I'll try again
